### ISSUE TITLE
The "reportSendError: "Got 422 status from server: UNPROCESSABLE ENTITY"" ping is wrongly sent after a problem is submitted

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/webcompat-blipz-experiment#154] opened 2018-10-31 15:43 UTC
**[Affected versions]:**
- Firefox Release 63
- Firefox Beta 64.0b5

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the following pref set:
- "extensions.webcompat-blipz-experiment.variation" string pref with "little-sentiment" value
- Have the Webcompat Blipz Experiment installed from [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1490261) 
- Have the browser console open (Ctrl+Shit+J). 

**[Steps to reproduce]:**
1. Open Firefox Release/Beta with the profile from the prerequisites.
2. Navigate to google.com and press the "ALT + SHIFT + P" keys.
3. Click the "I'm having problems" button.
4. Click on any of the problem types and then click the "Submit" button.
5. Observe the browser console.

**[Expected result]:**
- Only the "Would submit this report: " ping is displayed.

**[Actual results]:**
- A "reportSendError: "Got 422 status from server: UNPROCESSABLE" ping is sent.

**[Notes]:**
- The ping is sent after any 
- This issue is also reproducible on "more-sentiment" and "v1-more-context" branches.
- Attached a screen recording with the issue:

![rec of the issue - 420 error](https://user-images.githubusercontent.com/37875464/47800181-72de2880-dd34-11e8-9cc8-b2998bc5ca95.gif)

**Comment by wisniewskit** [comment] 2018-11-01 16:02
This is actually a duplicate of https://github.com/mozilla/webcompat-blipz-experiment-server/issues/47

@miketaylr, we should probably land that fix soon :)

**Closed by wisniewskit** 2018-11-01 16:02 UTC

**Comment by miketaylr** [comment] 2018-11-05 15:59
@Softvision-AndreeaCupsa the fix for this was deployed 10 minutes ago, please verify. Thanks.
